### ISSUE TITLE
Solve GitHub Scene Issue with Unity

### ISSUE THREAD

**Issue by rileycleavenger** [Andrew-Kohler/Daredevil64#3]
Solve the issue with scene files causing merge conflicts

**Comment by Jodiiiiiiii** [comment]
This forum discussion (https://forum.unity.com/threads/how-can-i-resolve-github-desktop-unity-merge-conflicts.1195684/) sort of outlines the problem and the general consensus I am seeing is that merge conflicts effectively cannot be resolved in any reasonable way. However, this is only an issue specifically with the scene files (.unity files) and is not an issue for any assets/scripts.

Because of this, my proposal is that during development we could either each have our own 'playground' scene to work within, OR we can use one and just make sure not to develop anything critical in it other than some basic environment for collision or interactible testing. As long as implemented mechanics are entirely stored within independent prefabs or scripts elsewhere the merge issues should not be a problem and we could somewhat arbitrarily override changes in the development/testing scene

Following this method we should be able to resolve any merge issues that emerge with a 'accept one change in its entirety and redo anything important in the overridden commits'

**Comment by rileycleavenger** [comment]
Solution: use dummy scenes
